// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/subscription/v1/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartTrialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrialRequest) Reset() {
	*x = StartTrialRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrialRequest) ProtoMessage() {}

func (x *StartTrialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrialRequest.ProtoReflect.Descriptor instead.
func (*StartTrialRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *StartTrialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ActivateOrRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanCode      string                 `protobuf:"bytes,2,opt,name=plan_code,json=planCode,proto3" json:"plan_code,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,3,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateOrRenewRequest) Reset() {
	*x = ActivateOrRenewRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateOrRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateOrRenewRequest) ProtoMessage() {}

func (x *ActivateOrRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateOrRenewRequest.ProtoReflect.Descriptor instead.
func (*ActivateOrRenewRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateOrRenewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivateOrRenewRequest) GetPlanCode() string {
	if x != nil {
		return x.PlanCode
	}
	return ""
}

func (x *ActivateOrRenewRequest) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

type GetActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveRequest) Reset() {
	*x = GetActiveRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveRequest) ProtoMessage() {}

func (x *GetActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveRequest.ProtoReflect.Descriptor instead.
func (*GetActiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Plan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceAmount       int64                  `protobuf:"varint,5,opt,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	DurationDays      int32                  `protobuf:"varint,7,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	DeviceLimit       int32                  `protobuf:"varint,8,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	TrafficLimitBytes *int64                 `protobuf:"varint,9,opt,name=traffic_limit_bytes,json=trafficLimitBytes,proto3,oneof" json:"traffic_limit_bytes,omitempty"`
	IsTrial           bool                   `protobuf:"varint,10,opt,name=is_trial,json=isTrial,proto3" json:"is_trial,omitempty"`
	IsActive          bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPriceAmount() int64 {
	if x != nil {
		return x.PriceAmount
	}
	return 0
}

func (x *Plan) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *Plan) GetTrafficLimitBytes() int64 {
	if x != nil && x.TrafficLimitBytes != nil {
		return *x.TrafficLimitBytes
	}
	return 0
}

func (x *Plan) GetIsTrial() bool {
	if x != nil {
		return x.IsTrial
	}
	return false
}

func (x *Plan) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Plan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Plan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,7,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	Trial         bool                   `protobuf:"varint,8,opt,name=trial,proto3" json:"trial,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Subscription) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Subscription) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *Subscription) GetTrial() bool {
	if x != nil {
		return x.Trial
	}
	return false
}

func (x *Subscription) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"(proto/subscription/v1/subscription.proto\x12\x0fsubscription.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x11StartTrialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"m\n" +
	"\x16ActivateOrRenewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tplan_code\x18\x02 \x01(\tR\bplanCode\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x03 \x01(\bR\tautoRenew\"+\n" +
	"\x10GetActiveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe2\x03\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fprice_amount\x18\x05 \x01(\x03R\vpriceAmount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12#\n" +
	"\rduration_days\x18\a \x01(\x05R\fdurationDays\x12!\n" +
	"\fdevice_limit\x18\b \x01(\x05R\vdeviceLimit\x123\n" +
	"\x13traffic_limit_bytes\x18\t \x01(\x03H\x00R\x11trafficLimitBytes\x88\x01\x01\x12\x19\n" +
	"\bis_trial\x18\n" +
	" \x01(\bR\aisTrial\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x16\n" +
	"\x14_traffic_limit_bytes\"\xc6\x03\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\a \x01(\bR\tautoRenew\x12\x14\n" +
	"\x05trial\x18\b \x01(\bR\x05trial\x12=\n" +
	"\fcancelled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x90\x02\n" +
	"\x13SubscriptionService\x12O\n" +
	"\n" +
	"StartTrial\x12\".subscription.v1.StartTrialRequest\x1a\x1d.subscription.v1.Subscription\x12Y\n" +
	"\x0fActivateOrRenew\x12'.subscription.v1.ActivateOrRenewRequest\x1a\x1d.subscription.v1.Subscription\x12M\n" +
	"\tGetActive\x12!.subscription.v1.GetActiveRequest\x1a\x1d.subscription.v1.SubscriptionBKZIgithub.com/Shyyw1e/The-Dark-Twenties/proto/subscription/v1;subscriptionv1b\x06proto3"

var (
	file_proto_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_v1_subscription_proto_rawDescData []byte
)

func file_proto_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_v1_subscription_proto_rawDesc), len(file_proto_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_v1_subscription_proto_rawDescData
}

var file_proto_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_subscription_v1_subscription_proto_goTypes = []any{
	(*StartTrialRequest)(nil),      // 0: subscription.v1.StartTrialRequest
	(*ActivateOrRenewRequest)(nil), // 1: subscription.v1.ActivateOrRenewRequest
	(*GetActiveRequest)(nil),       // 2: subscription.v1.GetActiveRequest
	(*Plan)(nil),                   // 3: subscription.v1.Plan
	(*Subscription)(nil),           // 4: subscription.v1.Subscription
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_proto_subscription_v1_subscription_proto_depIdxs = []int32{
	5,  // 0: subscription.v1.Plan.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: subscription.v1.Plan.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: subscription.v1.Subscription.starts_at:type_name -> google.protobuf.Timestamp
	5,  // 3: subscription.v1.Subscription.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 4: subscription.v1.Subscription.cancelled_at:type_name -> google.protobuf.Timestamp
	5,  // 5: subscription.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	5,  // 6: subscription.v1.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: subscription.v1.SubscriptionService.StartTrial:input_type -> subscription.v1.StartTrialRequest
	1,  // 8: subscription.v1.SubscriptionService.ActivateOrRenew:input_type -> subscription.v1.ActivateOrRenewRequest
	2,  // 9: subscription.v1.SubscriptionService.GetActive:input_type -> subscription.v1.GetActiveRequest
	4,  // 10: subscription.v1.SubscriptionService.StartTrial:output_type -> subscription.v1.Subscription
	4,  // 11: subscription.v1.SubscriptionService.ActivateOrRenew:output_type -> subscription.v1.Subscription
	4,  // 12: subscription.v1.SubscriptionService.GetActive:output_type -> subscription.v1.Subscription
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_subscription_v1_subscription_proto_init() }
func file_proto_subscription_v1_subscription_proto_init() {
	if File_proto_subscription_v1_subscription_proto != nil {
		return
	}
	file_proto_subscription_v1_subscription_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_v1_subscription_proto_rawDesc), len(file_proto_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_v1_subscription_proto = out.File
	file_proto_subscription_v1_subscription_proto_goTypes = nil
	file_proto_subscription_v1_subscription_proto_depIdxs = nil
}
